[project]
name = 'GigChain-Worker-Rights-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.fair-gig-rewards]
path = 'contracts/fair-gig-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.payment-protection-system]
path = 'contracts/payment-protection-system.clar'
clarity_version = 3
epoch = '3.2'

[contracts.rating-transparency-network]
path = 'contracts/rating-transparency-network.clar'
clarity_version = 3
epoch = '3.2'

[contracts.worker-profile-registry]
path = 'contracts/worker-profile-registry.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
